services:
  # Backend service
  - type: web
    name: gps-tracker-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production

  # Frontend static site
  - type: static
    name: gps-tracker-frontend
    buildCommand: echo "Static site, no build needed"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
